export const IS_USER_SIGNING_IN = 'IS_USER_SIGNING_IN';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_FAILURE';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
